#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Apr 22 14:46:43 2020

@author: vinny
"""

## Runfile for package

import datetime
import initial #initial questions for user




if __name__ == '__main__':
    initial.welcome()
    
    user_information = initial.initial_questions()
    
    
    print('')
    print('Nice to meet you', user_information.name)
    print('It seems that you are from', user_information.insitution)
    print('Your advisor is', user_information.advisor)
    print('You accessed this package on', user_information.date)